// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Target10._9.Persistence;

#nullable disable

namespace Target10._9.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250807102724_AddPointEntity")]
    partial class AddPointEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Target10._9.Business.Logs.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateLog")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Target10._9.Business.ModeDetails.Entities.ModeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("RestTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("ShootLimit")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("ShootingTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("ModeDetails");
                });

            modelBuilder.Entity("Target10._9.Business.Points.Entities.Point", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimePoint")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<float>("X_Coordinate")
                        .HasColumnType("real");

                    b.Property<float>("Y_Coordinate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("Target10._9.Business.SessionModeWeaponDetails.Entities.SessionModeWeaponDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionModeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeaponDetailsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionModeId");

                    b.HasIndex("WeaponDetailsId");

                    b.ToTable("SessionModeWeaponDetails");
                });

            modelBuilder.Entity("Target10._9.Business.SessionModes.Entities.SessionMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ModeDetailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("TimeLimits")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("WarmUp")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ModeDetailId");

                    b.ToTable("SessionModes");
                });

            modelBuilder.Entity("Target10._9.Business.Sessions.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionModeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionModeId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Target10._9.Business.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Target10._9.Business.WeaponDetails.Entities.WeaponDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeaponDetails");
                });

            modelBuilder.Entity("Target10._9.Business.Logs.Entities.Log", b =>
                {
                    b.HasOne("Target10._9.Business.Users.Entities.User", "Users")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Target10._9.Business.Points.Entities.Point", b =>
                {
                    b.HasOne("Target10._9.Business.Sessions.Entities.Session", "Session")
                        .WithMany("Points")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Target10._9.Business.SessionModeWeaponDetails.Entities.SessionModeWeaponDetail", b =>
                {
                    b.HasOne("Target10._9.Business.SessionModes.Entities.SessionMode", "SessionModes")
                        .WithMany("SessionModeWeaponDetails")
                        .HasForeignKey("SessionModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Target10._9.Business.WeaponDetails.Entities.WeaponDetail", "WeaponDetails")
                        .WithMany("SessionModeWeaponDetails")
                        .HasForeignKey("WeaponDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionModes");

                    b.Navigation("WeaponDetails");
                });

            modelBuilder.Entity("Target10._9.Business.SessionModes.Entities.SessionMode", b =>
                {
                    b.HasOne("Target10._9.Business.ModeDetails.Entities.ModeDetail", "ModeDetails")
                        .WithMany("SessionModes")
                        .HasForeignKey("ModeDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeDetails");
                });

            modelBuilder.Entity("Target10._9.Business.Sessions.Entities.Session", b =>
                {
                    b.HasOne("Target10._9.Business.SessionModes.Entities.SessionMode", "SessionModes")
                        .WithMany("Sessions")
                        .HasForeignKey("SessionModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Target10._9.Business.Users.Entities.User", "Users")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionModes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Target10._9.Business.WeaponDetails.Entities.WeaponDetail", b =>
                {
                    b.HasOne("Target10._9.Business.Users.Entities.User", "Users")
                        .WithMany("Weapons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Target10._9.Business.ModeDetails.Entities.ModeDetail", b =>
                {
                    b.Navigation("SessionModes");
                });

            modelBuilder.Entity("Target10._9.Business.SessionModes.Entities.SessionMode", b =>
                {
                    b.Navigation("SessionModeWeaponDetails");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Target10._9.Business.Sessions.Entities.Session", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("Target10._9.Business.Users.Entities.User", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Sessions");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("Target10._9.Business.WeaponDetails.Entities.WeaponDetail", b =>
                {
                    b.Navigation("SessionModeWeaponDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
