version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: target10_postgres
    restart: always
    environment:
      POSTGRES_USER: target_user
      POSTGRES_PASSWORD: target_password
      POSTGRES_DB: target_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - target10net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5 
  
  nginx:
    image: nginx:stable-alpine
    container_name: target10_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # Le dist fraîchement décompressé
      - ./web/dist:/usr/share/nginx/html:ro
      #- J:/Project/Target-10.9-web/dist:/usr/share/nginx/html:ro
      # Votre conf Nginx (à créer à côté du compose)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - target10net

volumes:
  dataprotectionkeys:
  postgres_data:

networks:
  target10net:
    driver: bridge
    
    
    
    