version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: target10_postgres
    restart: always
    environment:
      POSTGRES_USER: target_user
      POSTGRES_PASSWORD: target_password
      POSTGRES_DB: target_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - target10net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: target10_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=MaSuperCleSecreteUltraLongue1234567890
      - Jwt__Issuer=http://localhost
      - ASPNETCORE_URLS=http://+:5000
      - Jwt__Audience=http://localhost

      - POSTGRES_USER=target_user
      - POSTGRES_PASSWORD=target_password

      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=target_db;Username=target_user;Password=target_password
    ports:
      - "5000:5000"
    volumes:
      - dataprotectionkeys:/root/.aspnet/DataProtection-Keys
    networks:
      - target10net
  
  
  migrations:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: target10_migrations
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/src
    working_dir: /src/Target10.9.Api
    entrypoint: >
      sh -c "
        dotnet tool install --global dotnet-ef --version 9.* &&
        export PATH=\"$PATH:/root/.dotnet/tools\" &&
        dotnet ef database update \
          --project /src/Target10.9.Persistence/Target10.9.Persistence.csproj \
          --startup-project /src/Target10.9.Api/Target10.9.Api.csproj
      "
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=target_db;Username=target_user;Password=target_password
    networks:
      - target10net
  
  
  
  
  
  nginx:
    image: nginx:stable-alpine
    container_name: target10_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # Le dist fraîchement décompressé
      - ./web/dist:/usr/share/nginx/html:ro
      #- J:/Project/Target-10.9-web/dist:/usr/share/nginx/html:ro
      # Votre conf Nginx (à créer à côté du compose)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - target10net

volumes:
  dataprotectionkeys:
  postgres_data:

networks:
  target10net:
    driver: bridge
    
    
    
    