<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>Target10._9.Business</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="12.0.1" />
      <PackageReference Include="AutoMapper.Collection" Version="9.0.0" />
      <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
      <PackageReference Include="FluentValidation" Version="12.0.0" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.7" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6" />
      <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Authentications\" />
      <Folder Include="Points\Commands\" />
      <Folder Include="Points\Queries\" />
      <Folder Include="SessionModeWeaponDetails\Commands\" />
      <Folder Include="SessionModeWeaponDetails\Responses\" />
    </ItemGroup>

</Project>
